// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Dominio;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Dominio
{
    public partial class HRAContext
    {
        private HRAContextProcedures _procedures;

        public virtual HRAContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new HRAContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public HRAContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<usp_MenuLstResult>().HasNoKey().ToView(null);
            modelBuilder.Entity<usp_ReportePersonaResult>().HasNoKey().ToView(null);
        }
    }

    public interface IHRAContextProcedures
    {
        Task<List<usp_MenuLstResult>> usp_MenuLstAsync(int? UsuarioId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_ReportePersonaResult>> usp_ReportePersonaAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }

    public partial class HRAContextProcedures : IHRAContextProcedures
    {
        private readonly HRAContext _context;

        public HRAContextProcedures(HRAContext context)
        {
            _context = context;
        }

        public virtual async Task<List<usp_MenuLstResult>> usp_MenuLstAsync(int? UsuarioId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "UsuarioId",
                    Value = UsuarioId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<usp_MenuLstResult>("EXEC @returnValue = [MAESTRO].[usp_MenuLst] @UsuarioId", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<usp_ReportePersonaResult>> usp_ReportePersonaAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<usp_ReportePersonaResult>("EXEC @returnValue = [dbo].[usp_ReportePersona]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
