// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dominio
{
    public partial class PRODUCTO
    {
        public PRODUCTO()
        {
            DETALLE_VENTA = new HashSet<DETALLE_VENTA>();
        }

        public int IdProducto { get; set; }
        public string Codigo { get; set; }
        public int? IdCategoria { get; set; }
        public string Descripcion { get; set; }
        public decimal? PrecioCompra { get; set; }
        public decimal? PrecioVenta { get; set; }
        public int? Stock { get; set; }
        public DateTime? FechaRegistro { get; set; }

        public virtual CATEGORIA IdCategoriaNavigation { get; set; }
        public virtual ICollection<DETALLE_VENTA> DETALLE_VENTA { get; set; }
    }
}