// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Dominio
{
    public partial class usp_MenuLstResult
    {
        public int MenuId { get; set; }
        public string Denominacion { get; set; }
        public string Modulo { get; set; }
        public string Url { get; set; }
        public string Icono { get; set; }
        public bool? IndPadre { get; set; }
        public decimal? Orden { get; set; }
        public decimal? Referencia { get; set; }
    }
}
