// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Dominio
{
    public partial class usp_ReportePersonaResult
    {
        public int PersonaId { get; set; }
        public string NombreCompleto { get; set; }
        public string Celular { get; set; }
    }
}
