// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dominio
{
    public partial class VENTA
    {
        public VENTA()
        {
            DETALLE_VENTA = new HashSet<DETALLE_VENTA>();
        }

        public int IdVenta { get; set; }
        public string TipoPago { get; set; }
        public string NumeroDocumento { get; set; }
        public string DocumentoCliente { get; set; }
        public string NombreCliente { get; set; }
        public decimal? MontoPagoCon { get; set; }
        public decimal? MontoCambio { get; set; }
        public decimal? MontoSubTotal { get; set; }
        public decimal? MontoIGV { get; set; }
        public decimal? MontoTotal { get; set; }
        public DateTime? FechaRegistro { get; set; }

        public virtual ICollection<DETALLE_VENTA> DETALLE_VENTA { get; set; }
    }
}